#!/usr/bin/env bash
# installing nginx & configuring it to remote server

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
