#!/usr/bin/env bash
# installing nginx & configuring it to remote server

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "26i $line" /etc/nginx/sites-available/default
line="\\\trewrite ^/redirect_me http://HLBuep4qt.tech permanent"
sudo service nginx start
