#!/usr/bin/env bash
# installing nginx & configuring it to remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        location /redirect_me {
                return 301 https://web.facebook.com/;
        }
}"

sudo bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
       sudo service nginx start
else
        sudo service nginx restart
fi
