#!/usr/bin/env bash
# installing nginx & configuring it to remote server

sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "26i $line" /etc/nginx/sites-available/default
line="\\\trewrite ^/redirect_me http://cheslin.tech permanent;"
sudo service nginx restart
sudoufw allow 'Nginx HTTP'
