#!/usr/bin/env bash
# installing nginx & configuring it to remote server then redirecting

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;
   add_header X-Served-By \$hostname;
   location /redirect_me {
      return 301 https://web.facebook.com/;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
