#!/usr/bin/env bash
#loops from 1 to 10 and:

#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

total=0

while [ $total -lt 10 ]
do
	if [ $total -eq 3 ]
	then
		echo "bad luck"
	elif [ $total -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( total++ ))
done
